//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub artist_id: i32,
    #[sea_orm(unique)]
    pub spotify_id: Option<String>,
    pub musicbrainz_release_group_id: Option<String>,
    pub release_date: Option<Date>,
    pub total_tracks: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_art_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub genres: Option<String>,
    pub ownership_status: String,
    pub acquisition_source: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub local_path: Option<String>,
    pub match_score: Option<i32>,
    pub match_status: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_synced_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artists::Entity",
        from = "Column::ArtistId",
        to = "super::artists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Artists,
    #[sea_orm(has_many = "super::lidarr_downloads::Entity")]
    LidarrDownloads,
    #[sea_orm(has_many = "super::tracks::Entity")]
    Tracks,
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artists.def()
    }
}

impl Related<super::lidarr_downloads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LidarrDownloads.def()
    }
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
